name: template
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  get: 3.26.0

  datetime_picker_formfield: ^1.0.0
  intl: ^0.16.1
  flutter_screenutil: ^4.0.3+1
  flutter_svg: ^0.19.0
  google_fonts: ^1.1.2
  get_storage: ^1.4.0
  dio: ^3.0.10
  image_picker: ^0.6.7+22
  pin_code_fields: ^6.1.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/locale/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic